# Database TYPE: flatfile or mongodb
TYPE: flatfile
MONGO:
  HOST: '127.0.0.1'
  PORT: 27017
  DATABASE: 'fortune'
  AUTH:
    ENABLED: false
    USERNAME: 'user'
    PASSWORD: 'password'
    AUTH-DATABASE: 'admin'
# Colors: WHITE,YELLOW,GOLD,RED,DARK_RED,LIGHT_PURPLE(ITS PINK),PURPLE,AQUA,GREEN,BLUE,DARK_GRAY,GRAY,DARK_PURPLE(ITS PURPLE),DARK_RED,DARK_AQUA,DARK_GREEN,DARK_BLUE,BLACK
MAIN_COLOR: "GOLD"
SECONDARY_COLOR: "WHITE"
# BUNGEECORD
BUNGEECORD:
  ENABLED: false
  FALLBACK-SERVER: "Hub-1"
